title: Arunava Nag
logo: /assets/img/me.png
description: Data Scientist in Training | Bridging the Gap Between Insects and Real-World Applications
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
